name: Mosquitto - Build variants

on:
  push:
    branches:
      - master
      - develop
      - fixes
      - release/*
  pull_request:
    branches:
      - master
      - develop
      - fixes
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install third party dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          docbook-xsl \
          libargon2-dev \
          libc-ares-dev \
          libcjson-dev \
          libcunit1-dev \
          libedit-dev \
          libgmock-dev \
          libmicrohttpd-dev \
          libssl-dev \
          libsystemd-dev \
          libwrap0-dev \
          python3-all \
          uthash-dev \
          xsltproc
    - uses: actions/checkout@v6
      with:
        submodules: 'true'
    - name: build
      run: ./buildtest.py
