name: Mosquitto - Make

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - fixes
      - develop
      - release/*
    tags:
      - 'v[0-9]+.*'
  pull_request:
    branches:
      - master
      - fixes
      - develop
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install third party dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          docbook-xsl \
          lcov \
          libargon2-dev \
          libc-ares-dev \
          libcjson-dev \
          libcjson1 \
          libcunit1-dev \
          libedit-dev \
          libgmock-dev \
          libmicrohttpd-dev \
          libssl-dev \
          libwrap0-dev \
          microsocks \
          python3-all \
          python3-paho-mqtt \
          python3-psutil \
          uthash-dev \
          xsltproc
    -
      uses: actions/checkout@v6
      with:
        submodules: 'true'
    -
      name: make
      run: make
    -
      name: make test
      run: |
        make ptest
